### PR TITLE
Update tutorials.md

### PR DESCRIPTION
**Pull request by adamaze**
I'm suggesting this small change, as it confused me as I was setting up my respeaker 4-mic array. The drivers are really for any of their mic arrays, so I thought that this line could be better if it was generalized.

### CODE REVIEW

**Comment by koenvervloesem** [comment]
Good point. Maybe the link should also be generalized to https://respeaker.io/ instead of pointing to the 2-mic array?

**Comment by adamaze** [comment]
I didn't have a super strong preference at the time, but that sounds like a good idea

**Comment by koenvervloesem** [comment]
Great, can you change this? I'll merge the pull request then.

**Comment by koenvervloesem** [comment]
Thanks for your contribution, @adamaze! I hope you'll enjoy Rhasspy.

**Comment by synesthesiam** [comment]
Thanks @adamaze!

**Pull request merged**
